name: Endpoints Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies from requirements.txt
      run: |
        Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        .\compatibility\install.ps1

    - name: Run tests
      run: |
        python -m tests.endpoints
