name: Run Server on macOS

on: [push, pull_request]

jobs:
  run-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          chmod +x compatibility/install.sh
          ./compatibility/install.sh

      - name: Run script with 10s timeout
        run: |
          python3 app.py &
          PID=$!
          sleep 10
          kill $PID
        shell: bash
